apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

namePrefix: production-

patches:
  - path: deployment-patch.yaml
  - target:
      kind: HorizontalPodAutoscaler
      name: e2bgateway
    patch: |-
      - op: replace
        path: /spec/scaleTargetRef/name
        value: production-e2bgateway
