apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2bgateway.fullname" . }}
  labels:
    {{- include "e2bgateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "e2bgateway.selectorLabels" . | nindent 4 }}
